### ISSUE TITLE
An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

### ISSUE THREAD

**Issue by amatkivskiy** [MarcelBraghetto/Cheeseknife#3]
Hi, 
First of all many thanks for this library.
Recently I was developing an android library project that will be used in my android application. There was my custom fragment in this library. But after I've added **[InjectView(Resource.Id.layout_id)]** to this fragment I can't build my app due to compile error.

**error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type**

Is there any solution for this issue?

**Comment by LilarcorDev** [comment]
Hi there. This is actually a limitation of Android Library projects in general (I get the same kinds of problems when I'm doing Java based Android development with libraries such as Butterknife).

Basically, the resource identifiers inside an Android library are not 'final' and are therefore can't be processed as constants - which are a requirement of using annotated resource IDs.

Check this link for what this is about:

http://tools.android.com/tips/non-constant-fields

Unfortunately there is no workaround that I know of. It isn't a problem with the Cheeseknife library itself, just a quirk with resource identifiers inside Android Library projects. The most likely outcome for you would be that any code you have in an Android Library project will not be able to use Cheeseknife - and as I mentioned the same problem exists for Java based Android projects as well.

You should be able to continue to use Cheeseknife in any non-library Android project though.

Kind regards
Marcel.

**Comment by amatkivskiy** [comment]
Thanks for answer.
Maybe it would be better to mention somewhere in README that android library projects are not supported by Cheeseknife?

**Comment by LilarcorDev** [comment]
Yep thats a valid comment. I have updated the README markup to include information specifically about this.

Cheers
Marcel.

**Comment by amatkivskiy** [comment]
Ok, thanks for help.
