### ISSUE TITLE
Injection not working when using inheritance ?

### ISSUE THREAD

**Issue by Miiite** [MarcelBraghetto/Cheeseknife#7]
Hey guys,

I started using Cheeseknife very recently and it's working just fine on the first fragment I implemented with.

Now I'm trying to migrate another fragment, from a FindViewById pattern to the Cheeseknife syntax, and it seems I'm having issues making it work properly.

The fragment in question is actually an abstract class, inflating the root view, and then doing some event handling subscriptions. And if I call the Cheeseknife.Inject(this, view) in either the OnCreateView method of the abstract fragment, or the child classes of this class, all my views using InjectView are null.

Does anyone has the same issue ? Is it intended for some reason ? 

Thanks !

**Comment by interisti** [comment]
Hi,

maybe the problem is if you have marked your fields as private

**Comment by Miiite** [comment]
All my fields are private indeed. But they also are private in the working fragments (i.e those not using inheritance)
